port 26379
sentinel monitor keydb_master keydb_master 6379 1
sentinel auth-pass keydb_master 
sentinel down-after-milliseconds keydb_master 5000
sentinel failover-timeout keydb_master 60000
sentinel parallel-syncs keydb_master 1
sentinel deny-scripts-reconfig yes
