port 26379
sentinel monitor valkey_master valkey_master 6379 1
sentinel auth-pass valkey_master 
sentinel down-after-milliseconds valkey_master 5000
sentinel failover-timeout valkey_master 60000
sentinel parallel-syncs valkey_master 1
sentinel deny-scripts-reconfig yes
